apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: training
  name: volume-1
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volume-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: training
  name: volume-2
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volume-2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: training
  name: volume-3
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volume-3
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: training
  name: volume-4
spec:
  capacity:
    storage: 10G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/volume-4
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: training
  name: nginx-stateful-set
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: nginx
  serviceName: nginx-service
  template:
    metadata:
      labels:
        app-name: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.0-alpine
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: nginx-volume-claim
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: nginx-volume-claim
      spec:
        resources:
          requests:
            storage: 1G
        accessModes:
          - ReadWriteOnce
