apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: training
  name: sqrt-autoscaler
spec:
  minReplicas: 1
  maxReplicas: 10
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sqrt-deployment
  targetCPUUtilizationPercentage: 50
