apiVersion: v1
kind: Pod
metadata:
  namespace: training
  name: updater-pod
spec:
  containers:
    - name: nginx
      image: nginx:1.23.0-alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: storage
          mountPath: /usr/share/nginx/html
    - name: updater
      image: landrzejewski/updater:v2
      args:
        - '60'
#      env:
#        - name: INTERVAL
#          #value: '60'
#          valueFrom:
#            configMapKeyRef:
#              name: updater-config-map
#              key: INTERVAL
      envFrom:
        - configMapRef:
            name: updater-config-map
      volumeMounts:
        - name: storage
          mountPath: /var/htdocs

  volumes:
    - name: storage
      hostPath:
        path: /tmp/storage
